services:
  syslog-flow:
    build: .
    container_name: syslog-flow
    restart: unless-stopped
    ports:
      - "2200:2200"
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./logs:/logs
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
